name: generate animation

on:
  # kikhdam automaticament kola 24 sa3a
  schedule:
    - cron: "0 */24 * * *" 
  
  # t9der tkhdmo manuelment f ay weqt mn tab dial Actions
  workflow_dispatch:
  
  # kikhdam m3a kola push f main wla master
  push:
    branches:
    - main
    - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Generer l-animation dial snake
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: mouadziyani
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#ff0000&color_dots=#161b22,#b91c1c,#7f1d1d,#ef4444,#f87171
          
      # Push l-output l-wa7d l-branch jdida smitha 'output'
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
